# -*- coding: utf-8 -*-
"""doctor_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5EsA-Ve_tOwHZFELqSHiJmNeNmMdum7
"""

import streamlit as st
import base64
from groq import Groq

st.set_page_config(page_title="AI DOCTOR BRAIN", layout="centered")

st.title("🧠 AI DOCTOR BRAIN")
st.write("Upload a medical image (e.g., MRI, X-ray) and ask a diagnostic question.")

# Input: API Key
GROQ_API_KEY = st.text_input("Enter your GROQ API Key:", type="password")

# File Upload
uploaded_image = st.file_uploader("Upload an image (JPEG or PNG):", type=["jpg", "jpeg", "png"])

# Diagnostic Question
query = st.text_area("Ask a question about the image:")

# Analyze Button
if st.button("🩺 Analyze") and uploaded_image and query and GROQ_API_KEY:
    image_bytes = uploaded_image.read()
    encoded_image = base64.b64encode(image_bytes).decode("utf-8")

    client = Groq(api_key=GROQ_API_KEY)
    model = "meta-llama/llama-4-scout-17b-16e-instruct"

    messages = [{
        "role": "user",
        "content": [
            {"type": "text", "text": query},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{encoded_image}"}}
        ]
    }]

    with st.spinner("🔍 Analyzing image... please wait."):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages
            )
            st.success("✅ Analysis Complete!")
            st.markdown("**Diagnosis / Response:**")
            st.write(response.choices[0].message.content)

        except Exception as e:
            st.error(f"❌ Error: {e}")

